name: Format Check

# Run on all push and pull requests
on:
  push:
  pull_request:

jobs:
  format-check:
    name: Run format check
    uses: havencarlson/cFS/.github/workflows/format-check.yml@workflow-ubuntu-update