name: Static Analysis

# Run on all push and pull requests
on:
  push:
  pull_request:

jobs:
  static-analysis:
    name: Run cppcheck
    uses: havencarlson/cFS/.github/workflows/static-analysis.yml@workflow-ubuntu-update
    with: 
      strict-dir-list: './src/bsp ./src/os'
